//
//  OperationViewModel.swift
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-MVVM-Coordinator-template
//

import Foundation

class OperationViewModel: OperationViewModelInterface, ObservableObject {

    private var output: OperationModuleOutput?
    private var operation: NetworkViewer.Operation

    init(operation: NetworkViewer.Operation, output:OperationModuleOutput? = nil) {
        self.operation = operation
        self.output = output
    }
}

// MARK: - OperationModuleInput
extension OperationViewModel: OperationModuleInput { }
