//
//  OperationScreen.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-MVVM-Coordinator-template
//

import SwiftUI

struct OperationScreen: View, OperationView {

    @StateObject var viewModel: OperationViewModel

    var body: some View {
        Text("Hello")
            .onAppear {
                viewModel.viewWillAppear()
            }
    }
}

#Preview {
    let module = OperationConfigurator.createModule()
    return module.view
}
