//
//  OperationConfigurator.swift
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-MVVM-Coordinator-template
//

import UIKit
import SwiftUI

struct OperationConfigurator {

    static func createModule(
        operation: NetworkViewer.Operation,
        output: OperationModuleOutput? = nil
    ) -> (view: some View, input: OperationModuleInput) {
        let viewModel = OperationViewModel(operation: operation, output: output)
        let view = OperationScreen(viewModel: viewModel)

        return (view, viewModel)
    }
}
