//
//  OperationConfigurator.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-Coordinator-template
//

import UIKit
import SwiftUI

struct OperationConfigurator {

    static func createModule(
        output: OperationModuleOutput? = nil
    ) -> (view: some View, input: OperationModuleInput) {
        let interactor = OperationInteractor()
        let presenter = OperationPresenter(
            interactor: interactor,
            output: output
        )
        let view = OperationScreen(presenter: presenter)

        presenter.view = view
        interactor.presenter = presenter

        return (view, presenter)
    }
}
