//
//  OperationPresenter.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-Coordinator-template
//

import Foundation
import SwiftUI

final class OperationPresenter: ObservableObject {

    // MARK: - Properties
    var view: OperationView?
    var interactor: OperationInteractorInput
    private var output: OperationModuleOutput?

    // MARK: - Initialization and deinitialization
    init(
        interactor: OperationInteractorInput,
        output: OperationModuleOutput?
    ) {
        self.interactor = interactor
        self.output = output
    }
}

// MARK: - Actions
extension OperationPresenter: OperationPresenterInterface {

}

// MARK: - OperationInteractorOutput
extension OperationPresenter: OperationInteractorOutput {

}

// MARK: - OperationModuleInput
extension OperationPresenter: OperationModuleInput { }
