//
//  OperationInteractor.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-Coordinator-template
//

import Foundation

final class OperationInteractor: OperationInteractorInput {

    // MARK: - Properties
    weak var presenter: OperationInteractorOutput?

    // MARK: - OperationInteractorInput
}
