//
//  OperationViewModel.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-MVVM-Coordinator-template
//

import Foundation

class OperationViewModel: OperationViewModelInterface, ObservableObject {

    private var output: OperationModuleOutput?

    init(output:OperationModuleOutput? = nil) {
        self.output = output
    }
}

// MARK: - OperationModuleInput
extension OperationViewModel: OperationModuleInput { }
