//
//  BodyViewerScreen.swift
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-MVVM-Coordinator-template
//

import SwiftUI

struct BodyViewerScreen: View, BodyViewerView {

    enum TextDisplayStyle: String, CaseIterable, Identifiable {

        var id: Self {
            self
        }

        case json   = "JSON"
        case raw    = "RAW"
    }

    @StateObject var viewModel: BodyViewerViewModel
    @State private var textDisplayStyle: TextDisplayStyle
    @State private var isShowingFindNavigator = false

    init(viewModel: BodyViewerViewModel) {
        _viewModel = StateObject(wrappedValue: viewModel)
        if viewModel.isJSONValid {
            _textDisplayStyle = State(initialValue: .json)
        } else {
            _textDisplayStyle = State(initialValue: .raw)
        }
    }

    var body: some View {
        VStack {
            Picker("", selection: $textDisplayStyle) {
                ForEach(TextDisplayStyle.allCases) {
                    Text($0.rawValue)
                }
            }
            .pickerStyle(.segmented)
            contentForStyle(textDisplayStyle)
        }
        .padding([.leading, .trailing], 16)
        .toolbar {
            ToolbarItem(placement: .topBarTrailing) {
                HStack {
                    Button {
                        textDisplayStyle = .raw
                        // Hack to avoid bug with FindNavigator when TextEditor not always visibles
                        DispatchQueue.main.asyncAfter(deadline: .now() + 0.01) {
                            textDisplayStyle = .json
                            textDisplayStyle = .raw
                            isShowingFindNavigator.toggle()
                        }
                    } label: {
                        Image(systemName: "magnifyingglass")
                    }
                    
                    ShareOptionsView(data: viewModel.text)
                }
            }
        }
        .navigationTitle(viewModel.title)
        .onAppear {
            viewModel.viewWillAppear()
        }
        .onDisappear {
            isShowingFindNavigator = false
            UIApplication.endEditing()
        }
        .navigationBarTitleDisplayMode(.inline)
        .viFindNavigator(isPresented: $isShowingFindNavigator)
    }

    @ViewBuilder
    func contentForStyle(_ style: TextDisplayStyle) -> some View {
        switch style {
        case .json:
            DebugJsonView(viewModel.text)
        case .raw:
            TextEditor(text: .constant(viewModel.text))
                .font(Font(UIFont.monospacedSystemFont(ofSize: 13, weight: .medium)))
                .ignoresSafeArea(.container, edges: .bottom)
        }
    }
}

#Preview {
    let jsonData = """
{
    "glossary": {
        "title": "example glossary",
        "GlossDiv": {
            "title": "S",
            "GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
                    "SortAs": "SGML",
                    "GlossTerm": "Standard Generalized Markup Language",
                    "Acronym": "SGML",
                    "Abbrev": "ISO 8879:1986",
                    "GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
                        "GlossSeeAlso": ["GML", "XML"]
                    },
                    "GlossSee": "markup"
                }
            }
        }
    }
}
"""
//    let jsonData = "<html>Test</html>"
        .data(using: .utf8)
    let module = BodyViewerConfigurator.createModule(title: "Response", data: jsonData ?? .init())
    return NavigationView {
        module.view
    }
}
