//
//  BodyViewerViewModel.swift
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-MVVM-Coordinator-template
//

import Foundation

class BodyViewerViewModel: BodyViewerViewModelInterface, ObservableObject {

    private var output: BodyViewerModuleOutput?
    public let title: String
    public let text: String
    public let isJSONValid: Bool

    init(title: String, data: Data, output: BodyViewerModuleOutput? = nil) {
        self.title = title
        self.output = output
        if let jsonObject = data.jsonObject, let value = getJsonString(jsonObject: jsonObject) {
            self.text = value
            self.isJSONValid = true
        } else {
            self.text = String(data: data, encoding: .utf8) ?? "-"
            self.isJSONValid = false
        }
    }
}

// MARK: - BodyViewerModuleInput
extension BodyViewerViewModel: BodyViewerModuleInput { }
