//
//  BodyViewerViewModel.swift
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-MVVM-Coordinator-template
//

import Foundation

class BodyViewerViewModel: BodyViewerViewModelInterface, ObservableObject {

    private var output: BodyViewerModuleOutput?
    public let text: String

    init(data: Data, output: BodyViewerModuleOutput? = nil) {
        self.text = data.jsonObject?.getJsonString() ?? "-"
        self.output = output
    }
}

// MARK: - BodyViewerModuleInput
extension BodyViewerViewModel: BodyViewerModuleInput { }
