//
//  BodyViewerScreen.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-MVVM-Coordinator-template
//

import SwiftUI

struct BodyViewerScreen: View, BodyViewerView {

    @StateObject var viewModel: BodyViewerViewModel
    @State private var isShowingFindNavigator = false

    var body: some View {
        TextEditor(text: .constant(viewModel.text))
            .ignoresSafeArea(.container, edges: .bottom)
            .onAppear {
                viewModel.viewWillAppear()
            }
            .viFindNavigator(isPresented: $isShowingFindNavigator)
            .toolbar {
                if #available(iOS 16.0, *) {
                    Button {
                        isShowingFindNavigator.toggle()
                    } label: {
                        Image(systemName: "magnifyingglass")
                    }
                    ShareLink(items: [viewModel.text]) {
                        Image(systemName: "square.and.arrow.up")
                    }
                }
            }
    }
}

#Preview {
    let jsonData = """
{
    "glossary": {
        "title": "example glossary",
        "GlossDiv": {
            "title": "S",
            "GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
                    "SortAs": "SGML",
                    "GlossTerm": "Standard Generalized Markup Language",
                    "Acronym": "SGML",
                    "Abbrev": "ISO 8879:1986",
                    "GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
                        "GlossSeeAlso": ["GML", "XML"]
                    },
                    "GlossSee": "markup"
                }
            }
        }
    }
}
"""
        .data(using: .utf8)
    let module = BodyViewerConfigurator.createModule(data: jsonData ?? .init())
    return NavigationView {
        module.view
    }
}
