//
//  BodyViewerProtocols.swift
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-MVVM-Coordinator-template
//

import Foundation
import SwiftUI

// MARK: - BodyViewerModuleInput
protocol BodyViewerModuleInput: AnyObject { }

// MARK: - BodyViewerModuleOutput
struct BodyViewerModuleOutput {
    
//    let didSelectSearchResult: (_ searchResult: String) -> Void
}

// MARK: - Presenter
protocol BodyViewerViewModelInterface: ObservableObject {

    var text: String { get }

    // MARK: - Lifecycle
    func viewDidLoad()
    func viewWillAppear()
    func viewWillDisappear()
}

extension BodyViewerViewModelInterface {

    func viewDidLoad() {/*leaves this empty*/}
    func viewWillAppear() {/*leaves this empty*/}
    func viewWillDisappear() {/*leaves this empty*/}
}

// MARK: - View
protocol BodyViewerView {

}
