//
//  JSONViewerPresenter.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-Coordinator-template
//

import Foundation
import SwiftUI

final class JSONViewerPresenter: ObservableObject {

    // MARK: - Properties
    var view: JSONViewerView?
    var interactor: JSONViewerInteractorInput
    private var output: JSONViewerModuleOutput?

    // MARK: - Initialization and deinitialization
    init(
        interactor: JSONViewerInteractorInput,
        output: JSONViewerModuleOutput?
    ) {
        self.interactor = interactor
        self.output = output
    }
}

// MARK: - Actions
extension JSONViewerPresenter: JSONViewerPresenterInterface {

}

// MARK: - JSONViewerInteractorOutput
extension JSONViewerPresenter: JSONViewerInteractorOutput {

}

// MARK: - JSONViewerModuleInput
extension JSONViewerPresenter: JSONViewerModuleInput { }
