//
//  JSONViewerConfigurator.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-MVVM-Coordinator-template
//

import UIKit
import SwiftUI

struct JSONViewerConfigurator {

    static func createModule(
        output: JSONViewerModuleOutput? = nil
    ) -> (view: some View, input: JSONViewerModuleInput) {
        let viewModel = JSONViewerViewModel(output: output)
        let view = JSONViewerScreen(viewModel: viewModel)

        return (view, viewModel)
    }
}
