//
//  JSONViewerScreen.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-MVVM-Coordinator-template
//

import SwiftUI

struct JSONViewerScreen: View, JSONViewerView {

    @StateObject var viewModel: JSONViewerViewModel

    var body: some View {
        Text("Hello")
            .onAppear {
                viewModel.viewWillAppear()
            }
    }
}

#Preview {
    let module = JSONViewerConfigurator.createModule()
    return module.view
}
