//
//  JSONViewerProtocols.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-Coordinator-template
//

import Foundation
import SwiftUI

// MARK: - JSONViewerModuleInput
protocol JSONViewerModuleInput: AnyObject { }

// MARK: - JSONViewerModuleOutput
struct JSONViewerModuleOutput {
    
//    let didSelectSearchResult: (_ searchResult: String) -> Void
}

// MARK: - Presenter
protocol JSONViewerPresenterInterface: ObservableObject {

    // MARK: - Lifecycle
    func viewDidLoad()
    func viewWillAppear()
    func viewWillDisappear()
}

extension JSONViewerPresenterInterface {

    func viewDidLoad() {/*leaves this empty*/}
    func viewWillAppear() {/*leaves this empty*/}
    func viewWillDisappear() {/*leaves this empty*/}
}



// MARK: - Interactor
protocol JSONViewerInteractorOutput: AnyObject {

    /* Interactor -> Presenter */
}

protocol JSONViewerInteractorInput: AnyObject {

    var presenter: JSONViewerInteractorOutput? { get set }

    /* Presenter -> Interactor */
}

// MARK: - View
protocol JSONViewerView {

}
