//
//  JSONViewerViewModel.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-MVVM-Coordinator-template
//

import Foundation

class JSONViewerViewModel: JSONViewerViewModelInterface, ObservableObject {

    private var output: JSONViewerModuleOutput?

    init(output:JSONViewerModuleOutput? = nil) {
        self.output = output
    }
}

// MARK: - JSONViewerModuleInput
extension JSONViewerViewModel: JSONViewerModuleInput { }
