//
//  DomainListConfigurator.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-Coordinator-template
//

import UIKit
import SwiftUI

struct DomainListConfigurator {

    static func createModule(
        domainList: [DomainData],
        output: DomainListModuleOutput? = nil
    ) -> (view: some View, input: DomainListModuleInput) {
        let viewModel = DomainListViewModel(domainList: domainList, output: output)
        let view = DomainListScreen(viewModel: viewModel)

        return (view, viewModel)
    }
}
