//
//  DomainListScreen.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-Coordinator-template
//

import SwiftUI

struct DomainListScreen: View {

    @StateObject var viewModel: DomainListViewModel

    var body: some View {
        NavigationView {
            List(viewModel.domainsData, id: \.title) { data in
                CustomContentNavigationLink(
                    contentView: {
                        SettingsDetailedRow(data: data)
                    },
                    destination: {
                        OperationListConfigurator.createModule().view
                    }
                )
                .listRowInsets(.zero)
            }
            .navigationTitle("Domains")
        }
    }
}


#Preview {
    let domainList: [DomainData] = [
        .init(domain: "google.com", operationsCount: 4, isPinned: false),
        .init(domain: "apple.com", operationsCount: 23, isPinned: true),
        .init(domain: "medium.com", operationsCount: 9, isPinned: true),
        .init(domain: "youtube.com", operationsCount: 173, isPinned: false)
    ]
    let module = DomainListConfigurator.createModule(domainList: domainList)
    return module.view
}
