//
//  DomainListConfigurator.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-Coordinator-template
//

import UIKit
import SwiftUI

struct DomainListConfigurator {

    static func createModule(
        output: DomainListModuleOutput? = nil
    ) -> (view: some View, input: DomainListModuleInput) {
        let interactor = DomainListInteractor()
        let presenter = DomainListPresenter(
            interactor: interactor,
            output: output
        )
        let view = DomainListScreen(presenter: presenter)

        presenter.view = view
        interactor.presenter = presenter

        return (view, presenter)
    }
}
