//
//  DomainListScreen.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-Coordinator-template
//

import SwiftUI

struct DomainListScreen: View {

    @StateObject var viewModel: DomainListViewModel

    var body: some View {
        NavigationView {
            List() {
                sectionForDomains(isPinned: true)
                sectionForDomains(isPinned: false)
            }
            .navigationTitle("Domains")
        }
    }

    @ViewBuilder
    func sectionForDomains(isPinned: Bool) -> some View {
        let cellsData = isPinned
        ? viewModel.pinnedDomainCellsData
        : viewModel.unpinnedDomainCellsData
        if cellsData.isEmpty {
            EmptyView()
        } else {
            Section {
                ForEach(cellsData, id: \.id) { data in
                    CustomContentNavigationLink(
                        contentView: {
                            SettingsDetailedRow(data: data)
                        },
                        destination: {
                            OperationListConfigurator.createModule(operations: viewModel.operations(forId: data.id)).view
                        }
                    )
                    .listRowInsets(.zero)
                }
            } header: {
                if isPinned {
                    Text("isPinned")
                }
            } footer: { }
        }
    }
}


#Preview {
    let googleOperation = NetworkViewer.Operation(
        request: .init(url: "https://google.com", method: "POST", headers: [:], body: nil),
        response: nil,
        error: nil,
        startAt: Date().timeIntervalSince1970,
        endAt: Date().timeIntervalSince1970 + 60
    )
    let appleOperation = NetworkViewer.Operation(
        request: .init(url: "https://apple.com", method: "GET", headers: [:], body: nil),
        response: nil,
        error: nil,
        startAt: Date().timeIntervalSince1970 - 30,
        endAt: Date().timeIntervalSince1970 + 30
    )
    let appleSecondOperation = NetworkViewer.Operation(
        request: .init(url: "https://apple.com", method: "GET", headers: [:], body: nil),
        response: nil,
        error: nil,
        startAt: Date().timeIntervalSince1970 + 10,
        endAt: Date().timeIntervalSince1970 + 30
    )

    let operations: [NetworkViewer.Operation] = [
        googleOperation, appleOperation, googleOperation, appleSecondOperation, googleOperation
    ]
    let module = DomainListConfigurator.createModule(operations: operations)
    return module.view
}
