//
//  DomainListInteractor.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-Coordinator-template
//

import Foundation

final class DomainListInteractor: DomainListInteractorInput {

    // MARK: - Properties
    weak var presenter: DomainListInteractorOutput?

    // MARK: - DomainListInteractorInput
}
