//
//  DomainListPresenter.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-Coordinator-template
//

import Foundation
import SwiftUI

final class DomainListPresenter: ObservableObject {

    // MARK: - Properties
    var view: DomainListView?
    var interactor: DomainListInteractorInput
    private var output: DomainListModuleOutput?

    // MARK: - Initialization and deinitialization
    init(
        interactor: DomainListInteractorInput,
        output: DomainListModuleOutput?
    ) {
        self.interactor = interactor
        self.output = output
    }
}

// MARK: - Actions
extension DomainListPresenter: DomainListPresenterInterface {

}

// MARK: - DomainListInteractorOutput
extension DomainListPresenter: DomainListInteractorOutput {

}

// MARK: - DomainListModuleInput
extension DomainListPresenter: DomainListModuleInput { }
