//
//  DomainListConfigurator.swift
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-Coordinator-template
//

import UIKit
import SwiftUI

struct DomainListConfigurator {

    static func createModule(
        operations: [NetworkViewer.Operation],
        output: DomainListModuleOutput? = nil,
        shareService: ShareService
    ) -> (view: some View, input: DomainListModuleInput) {
        let viewModel = DomainListViewModel(operations: operations, output: output)
        let view = DomainListScreen(viewModel: viewModel)
            .environment(\.shareService, shareService)
        return (view, viewModel)
    }
}
