//
//  OperationListInteractor.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-Coordinator-template
//

import Foundation

final class OperationListInteractor: OperationListInteractorInput {

    // MARK: - Properties
    weak var presenter: OperationListInteractorOutput?

    // MARK: - OperationListInteractorInput
}
