//
//  OperationListConfigurator.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-MVVM-Coordinator-template
//

import UIKit
import SwiftUI

struct OperationListConfigurator {

    static func createModule(
        output: OperationListModuleOutput? = nil
    ) -> (view: some View, input: OperationListModuleInput) {
        let viewModel = OperationListViewModel(output: output)
        let view = OperationListScreen(viewModel: viewModel)

        return (view, viewModel)
    }
}
