//
//  OperationListConfigurator.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-Coordinator-template
//

import UIKit
import SwiftUI

struct OperationListConfigurator {

    static func createModule(
        output: OperationListModuleOutput? = nil
    ) -> (view: some View, input: OperationListModuleInput) {
        let interactor = OperationListInteractor()
        let presenter = OperationListPresenter(
            interactor: interactor,
            output: output
        )
        let view = OperationListScreen(presenter: presenter)

        presenter.view = view
        interactor.presenter = presenter

        return (view, presenter)
    }
}
