//
//  OperationListViewModel.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-MVVM-Coordinator-template
//

import Foundation

class OperationListViewModel: OperationListViewModelInterface, ObservableObject {

    private var output: OperationListModuleOutput?
    private let operations: [NetworkViewer.Operation]
    var title: String {
        URL(string: operations.first?.request.url ?? "")?.host ?? ""
    }

    init(operations: [NetworkViewer.Operation], output: OperationListModuleOutput? = nil) {
        self.operations = operations
        self.output = output
    }
}

// MARK: - OperationListModuleInput
extension OperationListViewModel: OperationListModuleInput { }
