//
//  OperationListPresenter.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-Coordinator-template
//

import Foundation
import SwiftUI

final class OperationListPresenter: ObservableObject {

    // MARK: - Properties
    var view: OperationListView?
    var interactor: OperationListInteractorInput
    private var output: OperationListModuleOutput?

    // MARK: - Initialization and deinitialization
    init(
        interactor: OperationListInteractorInput,
        output: OperationListModuleOutput?
    ) {
        self.interactor = interactor
        self.output = output
    }
}

// MARK: - Actions
extension OperationListPresenter: OperationListPresenterInterface {

}

// MARK: - OperationListInteractorOutput
extension OperationListPresenter: OperationListInteractorOutput {

}

// MARK: - OperationListModuleInput
extension OperationListPresenter: OperationListModuleInput { }
