//
//  OperationListProtocols.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-Coordinator-template
//

import Foundation
import SwiftUI

// MARK: - OperationListModuleInput
protocol OperationListModuleInput: AnyObject { }

// MARK: - OperationListModuleOutput
struct OperationListModuleOutput {
    
//    let didSelectSearchResult: (_ searchResult: String) -> Void
}

// MARK: - Presenter
protocol OperationListPresenterInterface: ObservableObject {

    // MARK: - Lifecycle
    func viewDidLoad()
    func viewWillAppear()
    func viewWillDisappear()
}

extension OperationListPresenterInterface {

    func viewDidLoad() {/*leaves this empty*/}
    func viewWillAppear() {/*leaves this empty*/}
    func viewWillDisappear() {/*leaves this empty*/}
}



// MARK: - Interactor
protocol OperationListInteractorOutput: AnyObject {

    /* Interactor -> Presenter */
}

protocol OperationListInteractorInput: AnyObject {

    var presenter: OperationListInteractorOutput? { get set }

    /* Presenter -> Interactor */
}

// MARK: - View
protocol OperationListView {

}
