//
//  OperationListScreen.swift
//  Olimp
//
//  Created Sakhabaev Egor on 10.11.2023.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/SwiftUI-Coordinator-template
//

import SwiftUI

struct OperationListScreen: View, OperationListView {

    @StateObject var presenter: OperationListPresenter

    var body: some View {
        Text("Hello")
            .onAppear {
                presenter.viewWillAppear()
            }
    }
}


#Preview {
    let module = OperationListConfigurator.createModule()
    return module.view
}
